fix: improve quote generator robustness (#52)
* refactor: create custom quote generation errors

* remove redundant import

* refactor: update create_report_data to return Result type

* refactor: update create_tdx_report to return Result type

* fix: add missing debug message

* refactor: update create_quote to return Result type

* refactor: update writing quote to propagate error

* refactor: update checking input size

* refactor: update reading arguments

* fix: remove unused modules

* fix: display error that does not implement std::error:Error

* fix: display error that does not implement std::error:Error

* refactor: change file name of the generated quote to incorporate report_data

* fix: apply fmt

* refactor: create a separate module for functions

* fix: add .vscode in .gitignore

* fix: add .vscode in .gitignore

* fix: return correct number of args

* refactor: declare constants in a dedicated file

* fix: make the call to create_tdx_report only in debug mode

* fix: replace println with debug